/*
Navicat MySQL Data Transfer

Source Server         : HuiJie
Source Server Version : 50631
Source Host           : 192.168.0.5:3306
Source Database       : emsb

Target Server Type    : MYSQL
Target Server Version : 50631
File Encoding         : 65001

Date: 2018-05-10 11:37:18
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for esb_ws
-- ----------------------------
DROP TABLE IF EXISTS `esb_ws`;
CREATE TABLE `esb_ws` (
  `id` varchar(128) NOT NULL,
  `soap_url` varchar(255) NOT NULL,
  `soap_action` varchar(255) NOT NULL,
  `req_info` text,
  `resp_info` text,
  `create_date` datetime DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `del_flag` char(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of esb_ws
-- ----------------------------
INSERT INTO `esb_ws` VALUES ('423dc551-c07f-4b97-b979-82147732cb24', 'http://180.76.165.24:8000/elisoft/eliservice', 'getOpResultForPackage', '<getOpResultForPackage xmlns=\"http://webservice.elisoft.com/\">\n            <areanum xmlns=\"\">2</areanum>\n            <currentPage xmlns=\"\">1</currentPage>\n            <pageNum xmlns=\"\">2</pageNum>\n        </getOpResultForPackage>', null, '2018-05-09 17:43:52', null, '0');
INSERT INTO `esb_ws` VALUES ('744a7ef7-6374-463e-938c-65245ea53c19', 'http://180.76.165.24:8000/elisoft/eliservice', 'getOpResultForPackage', '<getOpResultForPackage xmlns=\"http://webservice.elisoft.com/\">\n            <areanum xmlns=\"\">2</areanum>\n            <currentPage xmlns=\"\">1</currentPage>\n            <pageNum xmlns=\"\">2</pageNum>\n        </getOpResultForPackage>', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><ns2:getOpResultForPackageResponse xmlns:ns2=\"http://webservice.elisoft.com/\"><return>&lt;WebResponse&gt;\n  &lt;Header&gt;\n    &lt;TransactionID&gt;111250233&lt;/TransactionID&gt;\n    &lt;ResponseTime&gt;2018-05-10 10:47:59&lt;/ResponseTime&gt;\n    &lt;RetCode&gt;0&lt;/RetCode&gt;\n    &lt;RetDesc&gt;成功&lt;/RetDesc&gt;\n  &lt;/Header&gt;\n  &lt;WebBody&gt;\n    &lt;RetInfo&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2017-03-22 14:52&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;0&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;4061046&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2016-11-07 09:42&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;1&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;3340619&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;Total&gt;13083&lt;/Total&gt;\n    &lt;/RetInfo&gt;\n  &lt;/WebBody&gt;\n&lt;/WebResponse&gt;</return></ns2:getOpResultForPackageResponse>', '2018-05-10 10:45:49', '2018-05-10 10:46:47', '0');
INSERT INTO `esb_ws` VALUES ('81470215-af0b-4a90-a1e2-e520bacf2e18', 'http://180.76.165.24:8000/elisoft/eliservice', 'getOpResultForPackage', '<getOpResultForPackage xmlns=\"http://webservice.elisoft.com/\">\n            <areanum xmlns=\"\">2</areanum>\n            <currentPage xmlns=\"\">1</currentPage>\n            <pageNum xmlns=\"\">2</pageNum>\n        </getOpResultForPackage>', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><ns2:getOpResultForPackageResponse xmlns:ns2=\"http://webservice.elisoft.com/\"><return>&lt;WebResponse&gt;\n  &lt;Header&gt;\n    &lt;TransactionID&gt;111177341&lt;/TransactionID&gt;\n    &lt;ResponseTime&gt;2018-05-09 17:59:53&lt;/ResponseTime&gt;\n    &lt;RetCode&gt;0&lt;/RetCode&gt;\n    &lt;RetDesc&gt;成功&lt;/RetDesc&gt;\n  &lt;/Header&gt;\n  &lt;WebBody&gt;\n    &lt;RetInfo&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2017-03-22 14:52&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;0&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;4061046&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2016-11-07 09:42&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;1&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;3340619&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;Total&gt;13083&lt;/Total&gt;\n    &lt;/RetInfo&gt;\n  &lt;/WebBody&gt;\n&lt;/WebResponse&gt;</return></ns2:getOpResultForPackageResponse>', '2018-05-09 17:59:51', '2018-05-09 18:00:35', '0');
INSERT INTO `esb_ws` VALUES ('83d9eca8-0ab5-49a2-a0f4-b81666dd1b49', 'http://180.76.165.24:8000/elisoft/eliservice', 'getOpResultForPackage', '<getOpResultForPackage xmlns=\"http://webservice.elisoft.com/\">\n            <areanum xmlns=\"\">2</areanum>\n            <currentPage xmlns=\"\">1</currentPage>\n            <pageNum xmlns=\"\">2</pageNum>\n        </getOpResultForPackage>', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><ns2:getOpResultForPackageResponse xmlns:ns2=\"http://webservice.elisoft.com/\"><return>&lt;WebResponse&gt;\n  &lt;Header&gt;\n    &lt;TransactionID&gt;111250068&lt;/TransactionID&gt;\n    &lt;ResponseTime&gt;2018-05-10 10:41:36&lt;/ResponseTime&gt;\n    &lt;RetCode&gt;0&lt;/RetCode&gt;\n    &lt;RetDesc&gt;成功&lt;/RetDesc&gt;\n  &lt;/Header&gt;\n  &lt;WebBody&gt;\n    &lt;RetInfo&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2017-03-22 14:52&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;0&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;4061046&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2016-11-07 09:42&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;1&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;3340619&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;Total&gt;13083&lt;/Total&gt;\n    &lt;/RetInfo&gt;\n  &lt;/WebBody&gt;\n&lt;/WebResponse&gt;</return></ns2:getOpResultForPackageResponse>', '2018-05-10 10:37:23', '2018-05-10 10:42:18', '0');
INSERT INTO `esb_ws` VALUES ('da3dda63-2fc4-4a42-9403-717ccc3641b3', 'http://180.76.165.24:8000/elisoft/eliservice', 'getOpResultForPackage', '<getOpResultForPackage xmlns=\"http://webservice.elisoft.com/\">\n            <areanum xmlns=\"\">2</areanum>\n            <currentPage xmlns=\"\">1</currentPage>\n            <pageNum xmlns=\"\">2</pageNum>\n        </getOpResultForPackage>', '<?xml version=\"1.0\" encoding=\"UTF-8\"?><ns2:getOpResultForPackageResponse xmlns:ns2=\"http://webservice.elisoft.com/\"><return>&lt;WebResponse&gt;\n  &lt;Header&gt;\n    &lt;TransactionID&gt;111175937&lt;/TransactionID&gt;\n    &lt;ResponseTime&gt;2018-05-09 17:52:00&lt;/ResponseTime&gt;\n    &lt;RetCode&gt;0&lt;/RetCode&gt;\n    &lt;RetDesc&gt;成功&lt;/RetDesc&gt;\n  &lt;/Header&gt;\n  &lt;WebBody&gt;\n    &lt;RetInfo&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2017-03-22 14:52&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;0&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;4061046&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;OrderList&gt;\n        &lt;ResName&gt;3元移动数据流量套餐叠加包会员版&lt;/ResName&gt;\n        &lt;CreateTime&gt;2016-11-07 09:42&lt;/CreateTime&gt;\n        &lt;PhoneCount&gt;1&lt;/PhoneCount&gt;\n        &lt;SuccessCount&gt;1&lt;/SuccessCount&gt;\n        &lt;TodoCount&gt;0&lt;/TodoCount&gt;\n        &lt;Channel&gt;2&lt;/Channel&gt;\n        &lt;OrderId&gt;3340619&lt;/OrderId&gt;\n      &lt;/OrderList&gt;\n      &lt;Total&gt;13083&lt;/Total&gt;\n    &lt;/RetInfo&gt;\n  &lt;/WebBody&gt;\n&lt;/WebResponse&gt;</return></ns2:getOpResultForPackageResponse>', '2018-05-09 17:50:06', '2018-05-09 17:50:54', '0');
